// Code generated by raiden-cli; DO NOT EDIT.
package bootstrap

import (
	"apimedpoint/internal/controllers"
	"github.com/sev-2/raiden"
	raiden_controllers "github.com/sev-2/raiden/pkg/controllers"
	"github.com/valyala/fasthttp"
)

func RegisterRoute(server *raiden.Server) {
	server.RegisterRoute([]*raiden.Route{
		raiden.NewRouteFromController(&raiden_controllers.StateReadyController{}, []string{fasthttp.MethodPost}),
		{
			Type:       raiden.RouteTypeCustom,
			Path:       "/books",
			Methods:    []string{fasthttp.MethodGet},
			Controller: &controllers.BooksController{},
		},
		{
			Type:       raiden.RouteTypeCustom,
			Path:       "/hello/{name}",
			Methods:    []string{fasthttp.MethodGet},
			Controller: &controllers.HelloWordController{},
		},
		{
			Type:       raiden.RouteTypeCustom,
			Path:       "/users",
			Methods:    []string{fasthttp.MethodGet},
			Controller: &controllers.UserController{},
		},
	})
}
